// delegates/DocEditorDelegate.ts

import { Elements } from '../enums/Elements';
import { BaseDelegate } from './BaseDelegate';
import { IDelegate } from './IDelegate';

/**
 * Delegate responsible for DOM retrieval on the Document Editor page (`/docs/edit.php`).
 * Handles TinyMCE toolbars, title inputs, and header text.
 */
export const DocEditorDelegate: IDelegate = {
    ...BaseDelegate,

    /**
     * Primary retrieval method for single elements.
     * @param key - The Element Enum representing the UI component to fetch.
     * @param doc - A document override if the delegate is supposed to be fetching from another window.
     * @returns The DOM element corresponding to the key, or null if not found.
     */
    getElement(key: Elements, doc: Document = document): HTMLElement | null {
        switch (key) {
            case Elements.EDITOR_TOOLBAR:
                // Previous ID (#mceu_15-body) was fragile/auto-generated.
                // We now target the specific button group container using its stable classes.
                // This targets the first main toolbar group where standard buttons reside.
                // The child here is the autogenerated previous ID. Its existence is guaranteed.
                // Trust me bro!
                const toolbar = doc.querySelector('.mce-container.mce-flow-layout-item.mce-btn-group');
                if (toolbar) {
                    return toolbar.firstChild as HTMLElement;
                }
                return null;

            case Elements.EDITOR_HEADER_LABEL:
                // The header usually looks like "Edit Document: Title - WordCount"
                return doc.querySelector("div.tcat b");

            case Elements.EDITOR_TITLE_INPUT:
                return doc.querySelector("input[name='title']");

            default:
                return null;
        }
    },
};